# Generated by Django 4.0 on 2022-04-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aereo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=50, null=True, unique=True)),
                ('modello', models.CharField(max_length=50, null=True, unique=True)),
                ('stato', models.CharField(choices=[('In volo', 'In volo'), ('Pronto', 'Pronto'), ('Manutenzione', 'Manutenzione')], max_length=50, null=True)),
                ('km_totali', models.IntegerField(null=True)),
                ('km_da_ultima_manutenzione', models.IntegerField(null=True)),
                ('data_ultima_manutenzione', models.DateField(null=True)),
                ('posti_prima_classe', models.IntegerField()),
                ('posti_seconda_classe', models.IntegerField()),
                ('posti_terza_classe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=200, null=True, unique=True)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('descrizione', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzo_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('citta', models.CharField(max_length=100, null=True)),
                ('provincia', models.CharField(max_length=2, null=True)),
                ('stato', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('ora', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=200, null=True, unique=True)),
                ('prezzo_unitario_prima_classe', models.FloatField(default=0.0, null=True)),
                ('prezzo_unitario_seconda_classe', models.FloatField(default=0.0, null=True)),
                ('prezzo_unitario_terza_classe', models.FloatField(default=0.0, null=True)),
                ('ora_di_partenza', models.TimeField()),
                ('ora_di_arrivo', models.TimeField()),
                ('data_di_partenza', models.DateField(null=True)),
                ('data_di_arrivo', models.DateField(null=True)),
                ('km', models.FloatField(null=True)),
                ('aereo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aereo')),
                ('aeroporto_di_arrivo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_arrivo', to='App.aeroporto')),
                ('aeroporto_di_partenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_partenza', to='App.aeroporto')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=200, unique=True)),
                ('posti_prenotati', models.CharField(max_length=10, null=True)),
                ('prezzo_totale', models.FloatField(null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utente')),
                ('volo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.volo')),
            ],
        ),
        migrations.CreateModel(
            name='Posti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posti_prima_classe', models.IntegerField(null=True)),
                ('posti_seconda_classe', models.IntegerField(null=True)),
                ('posti_terza_classe', models.IntegerField(null=True)),
                ('aereo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aereo')),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=200, null=True, unique=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('stipendio', models.FloatField(default=0.0, null=True)),
                ('stato', models.CharField(choices=[('In volo', 'In volo'), ('Disponibile', 'Disponibile'), ('Ferie', 'Ferie'), ('Malattia', 'Malattia')], max_length=50, null=True)),
                ('ruolo', models.CharField(choices=[('pilota', 'Pilota'), ('Co-pilota', 'Co-pilota'), ('Hostess', 'Hostess')], max_length=50, null=True)),
                ('aereo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aereo')),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzo_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('citta', models.CharField(max_length=100, null=True)),
                ('provincia', models.CharField(max_length=2, null=True)),
                ('stato', models.CharField(max_length=100, null=True)),
                ('personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.personale')),
            ],
        ),
        migrations.CreateModel(
            name='Has_turni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.personale')),
                ('turni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.turni')),
            ],
        ),
        migrations.AddField(
            model_name='aeroporto',
            name='indirizzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.indirizzo_a'),
        ),
    ]
