# Generated by Django 4.0.3 on 2022-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='posti_prenotati',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
