# Generated by Django 4.0 on 2022-03-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aereo',
            old_name='prima_classe',
            new_name='posti_prima_classe',
        ),
        migrations.RenameField(
            model_name='aereo',
            old_name='seconda_classe',
            new_name='posti_seconda_classe',
        ),
        migrations.RenameField(
            model_name='aereo',
            old_name='terza_classe',
            new_name='posti_terza_classe',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='data_a',
            new_name='data_arrivo',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='data_p',
            new_name='data_partenza',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='ora_a',
            new_name='ora_arrivo',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='ora_p',
            new_name='ora_partenza',
        ),
    ]
