# Generated by Django 4.0.3 on 2022-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_prenotazioni_posti_prenotati'),
    ]

    operations = [
        migrations.AddField(
            model_name='volo',
            name='posti_prima_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volo',
            name='posti_seconda_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volo',
            name='posti_terza_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
