# Generated by Django 4.0.3 on 2022-04-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_volo_posti_prima_classe_volo_posti_seconda_classe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volo',
            old_name='posti_prima_classe',
            new_name='posti_totali',
        ),
        migrations.RemoveField(
            model_name='volo',
            name='posti_seconda_classe',
        ),
        migrations.RemoveField(
            model_name='volo',
            name='posti_terza_classe',
        ),
    ]
