# Generated by Django 4.0.3 on 2022-03-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='cognome',
            new_name='password',
        ),
    ]
