# Generated by Django 4.0.3 on 2022-04-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_posti_prima_classe_volo_posti_totali_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aereo',
            old_name='targa',
            new_name='codice',
        ),
    ]
