# Generated by Django 4.0.3 on 2022-03-25 13:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_cognome_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='personale',
            name='stipendio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personale',
            name='telefono',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='volo',
            name='prezzo_unitario',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Prenota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posti_prenotati', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utente')),
                ('volo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.volo')),
            ],
        ),
    ]
