# Generated by Django 4.0.3 on 2022-04-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_targa_aereo_codice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indirizzo_p',
            name='personale',
        ),
        migrations.RemoveField(
            model_name='personale',
            name='aereo',
        ),
        migrations.RemoveField(
            model_name='posti',
            name='aereo',
        ),
        migrations.DeleteModel(
            name='Has_turni',
        ),
        migrations.DeleteModel(
            name='Indirizzo_p',
        ),
        migrations.DeleteModel(
            name='Personale',
        ),
        migrations.DeleteModel(
            name='Posti',
        ),
        migrations.DeleteModel(
            name='Turni',
        ),
    ]
