# Generated by Django 4.0.3 on 2022-03-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_utente_personale_stipendio_personale_telefono_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prenota',
            new_name='Prenotazioni',
        ),
    ]
