# Generated by Django 4.0.3 on 2022-03-25 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_prenota_prenotazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='data_ultima_manutenzione',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='km_da_ultima_manutenzione',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='km_totali',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='modello',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='posti_prima_classe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='posti_seconda_classe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='posti_terza_classe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='stato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aereo',
            name='targa',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='codice',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='descrizione',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='citta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='numero',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='provincia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='stato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='via',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='codice',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='cognome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='ruolo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='stato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='stipendio',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='telefono',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazioni',
            name='posti_prenotati',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='turni',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turni',
            name='ora',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='cognome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='codice',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='data_arrivo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='data_partenza',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='ora_arrivo',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='ora_partenza',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volo',
            name='prezzo_unitario',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
