# Generated by Django 4.0.3 on 2022-04-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_indirizzo_p_personale_remove_personale_aereo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
