# Generated by Django 4.0 on 2022-04-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='codice',
            field=models.CharField(max_length=200),
        ),
    ]
