# Generated by Django 4.0.3 on 2022-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_volo_ora_arrivo_alter_volo_ora_partenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volo',
            name='ora_arrivo',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='volo',
            name='ora_partenza',
            field=models.TimeField(),
        ),
    ]
