# Generated by Django 4.0 on 2022-03-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_volo_ora_arrivo_alter_volo_ora_partenza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volo',
            name='aeroporto',
        ),
        migrations.AddField(
            model_name='volo',
            name='aeroporto_arrivo',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_arrivo', to='App.aeroporto'),
        ),
        migrations.AddField(
            model_name='volo',
            name='aeroporto_partenza',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_partenza', to='App.aeroporto'),
        ),
    ]
