# Generated by Django 4.0 on 2022-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_personale_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aereo',
            name='stato',
            field=models.CharField(choices=[('In volo', 'In volo'), ('Pronto', 'Pronto'), ('Manutenzione', 'Manutenzione')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='ruolo',
            field=models.CharField(choices=[('pilota', 'Pilota'), ('Co-pilota', 'Co-pilota'), ('Hostess', 'Hostess')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personale',
            name='stato',
            field=models.CharField(choices=[('In volo', 'In volo'), ('Disponibile', 'Disponibile'), ('Ferie', 'Ferie'), ('Malattia', 'Malattia')], max_length=50, null=True),
        ),
    ]
