# Generated by Django 4.0 on 2022-03-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_volo_aeroporto_partenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='volo',
            name='aeroporto_arrivo',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_arrivo', to='App.aeroporto'),
        ),
        migrations.AlterField(
            model_name='volo',
            name='aeroporto_partenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_partenza', to='App.aeroporto'),
        ),
    ]
