# Generated by Django 4.0 on 2022-03-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_volo_aeroporto_arrivo_delete_has_volo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volo',
            name='aeroporto_arrivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aeroporto_arrivo', to='App.aeroporto'),
        ),
    ]
