# Generated by Django 4.0.3 on 2022-03-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_volo_aeroporto_arrivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indirizzo',
            name='personale',
        ),
        migrations.AddField(
            model_name='personale',
            name='indirizzo',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='App.indirizzo'),
        ),
    ]
