# Generated by Django 4.0 on 2022-03-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_indirizzo_personale_personale_indirizzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personale',
            name='indirizzo',
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='personale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.personale'),
        ),
    ]
