# Generated by Django 4.0 on 2022-03-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_personale_indirizzo_indirizzo_personale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirizzo',
            name='personale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.personale'),
        ),
    ]
