# Generated by Django 4.0 on 2022-03-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_indirizzo_personale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirizzo_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('citta', models.CharField(max_length=100, null=True)),
                ('provincia', models.CharField(max_length=2, null=True)),
                ('stato', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Indirizzo',
            new_name='Indirizzo_p',
        ),
        migrations.AlterField(
            model_name='aeroporto',
            name='indirizzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.indirizzo_a'),
        ),
    ]
