# Generated by Django 4.0 on 2022-03-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_remove_aereo_posti_prima_classe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volo',
            old_name='aeroporto_arrivo',
            new_name='aeroporto_di_arrivo',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='aeroporto_partenza',
            new_name='aeroporto_di_partenza',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='data_arrivo',
            new_name='data_di_arrivo',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='data_partenza',
            new_name='data_di_partenza',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='ora_arrivo',
            new_name='ora_di_arrivo',
        ),
        migrations.RenameField(
            model_name='volo',
            old_name='ora_partenza',
            new_name='ora_di_partenza',
        ),
    ]
