# Generated by Django 4.0.3 on 2022-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_rename_aeroporto_arrivo_volo_aeroporto_di_arrivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazioni',
            name='codice',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
