# Generated by Django 4.0.3 on 2022-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_personale_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aereo',
            name='posti_prima_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aereo',
            name='posti_seconda_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aereo',
            name='posti_terza_classe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
