# Generated by Django 4.0.3 on 2022-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_aereo_posti_prima_classe_aereo_posti_seconda_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazioni',
            name='prezzo_totale',
            field=models.FloatField(null=True),
        ),
    ]
