# Generated by Django 4.0 on 2022-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_prenotazioni_prezzo_totale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazioni',
            name='posti_prenotati',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
